version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:${POSTGRES_VERSION}
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432
    networks:
      - sso-network
    volumes:
      - /home/${NAME_PROJECT}/data/db:/var/lib/postgresql/data/

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgresql
      DB_ADDR: postgresql
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASS}
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ueeHWugC!
      PROXY_ADDRESS_FORWARDING: "true"
      REDIRECT_SOCKET: "proxy-https"
      KEYCLOAK_FRONTEND_URL: https://sso.becloud.by
      TZ: ${TIME_ZONE}
    image: bitnami/keycloak:${KEYCLOAK_VERSION}
    ports:
      - 8080:8080
    networks:
      - sso-network


# Networks to be created to facilitate communication between containers
networks:
  sso-network:
    external: true
