version: '3.9'

services:
  nginx_proxy:
    image: nginx:${NGINX_VERSION}
    container_name: nginx_proxy
    restart: always
    volumes:
      - /home/${NAME_PROJECT}/nginx:/etc/nginx
      - /home/${NAME_PROJECT}/nginx/www:/data/www
      - /home/${NAME_PROJECT}/certs:/etc/letsencrypt
    environment:
      TZ: ${TIME_ZONE}
    ports:
      - 80:80
      - 443:443

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgresql
    restart: always
    environment:      
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432
    volumes:
      - /home/${NAME_PROJECT}/data/db:/var/lib/postgresql/data/

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASS}
      DB_PORT: 5432
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: ${USER}
      KEYCLOAK_ADMIN_PASSWORD: ${PASS}
      PROXY_ADDRESS_FORWARDING: true
      TZ: ${TIME_ZONE}
    image: bitnami/keycloak:${KEYCLOAK_VERSION}    
    ports:
      - 8080:8080
