version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - /home/${NAME_PROJECT}/nginx:/etc/nginx/conf.d
      - /home/${NAME_PROJECT}/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
        - sso-network
# Networks to be created to facilitate communication between containers
networks:
  sso-network:
    external: true
