name: CI
on: push
jobs:
  lint:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: mvn ci
      - name: Lint
        run: mvn run lint
